import type { Metadata } from "next";
import { PT_Sans } from "next/font/google";
import "./styles/globals.scss";
import Header from "./components/header/header";
import Footer from "./components/footer/footer";

const pt_sans = PT_Sans(
  {
    weight: ['400', '700'],
    subsets: ["cyrillic", "latin"],
    display: 'swap',
  },
  
);

export const metadata: Metadata = {
  title: "Frontend Pharmacy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={pt_sans.className}>
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  );
}
